### ISSUE TITLE
AssertionError inside linkstatetask

### ISSUE THREAD

**Issue by runborg** [Uninett/zino#263]
A traceback observed while parsing logs. i do not know why this has happened or the circumstances around it. 

```
ENTRY: Traceback (most recent call last):
  File "/home/runarb/zino2/zino-env/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/runarb/zino2/zino-env/lib/python3.10/site-packages/zino/tasks/linkstatetask.py", line 75, in poll_single_interface
    assert all(ident.index == OID(f".{ifindex}") for ident, value in result)
AssertionError

COUNT: 1
CC: ['2024-06-19 10:50:35,847 - ERROR - apscheduler.executors.default (MainThread) - Job "<redacted>-verify-569-state (trigger: date[2024-06-19 10:50:34 CEST], next run at: 2024-06-19 10:50:34 CEST)" raised an exception']
```

**Comment by lunkwill42** [comment]
This problem was still there, and was reported again by @he2.

Essentially, this amounts to Zino 2 being unnecessarily loud (and unspecific) about an interface gone missing between a trap and a single interface poll operation.  Zino 1 simply logs that the interface disappeared, while Zino 2 is being a loud-mouth about it.  Working on a fix.
